version: "3.9"
services:
  web:
    image: singup-react-image
    build: ../../sing-app-react
    ports:
       - "3000:3000"
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=development
    ports:
      - "5432:5432"
  backend:
    image: user-management-nodejs-backend-image
    volumes:
      - ./wait-for-it.sh:/usr/src/app/wait-for-it.sh
      - ./start-backend.sh:/usr/src/app/start-backend.sh
    build: ../
    environment:
     - DEV_DB_HOST=db
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:5432", "--timeout=0", "--strict", "--", "./start-backend.sh"]